baseURL = 'https://baseba.github.io'
languageCode = 'es-cl'
title = 'Sebastian Espejo'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Welcome to my personal page"
Content = "Here you can find info about my projects and myself"

[[params.socialIcons]]
name = "github"
url = "https://github.com/baseba"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/baseba"
